#!/usr/bin/env bash

set -eu

if [ $1 == "hs" ]; then
    cd "$WD/build"
    for f in src/BreakpointTree.hs src/Fortune.hs src/Main.hs; do
        cp "$WD/$f" ./
    done
    ghc -Wall BreakpointTree.hs Fortune.hs Main.hs -o "$WD/bin/hs"

    "$WD/bin/hs"
else
    cd "$WD/build"
    for f in src/breakpoint.ml src/psqueue.ml src/fortune.ml src/main.ml; do
        cp "$WD/$f" ./
    done
    ocamlfind \
        ocamlc \
        breakpoint.ml psqueue.ml fortune.ml \
        -w +1..66-4-42 \
        -package psq \
        -linkpkg main.ml \
        -o "$WD/bin/ml"

    "$WD/bin/ml"
fi
