#!/usr/bin/env bash

set -e

xs=(
    src/components.ml
    src/main.ml
)

cd "$WD/build"
for f in "${xs[@]}"; do
    cp "$WD/$f" ./
done
ocamlfind \
    ocamlc \
    components.ml \
    -w +1..66 \
    -linkpkg main.ml \
    -o "$WD/bin/grafs"

cd "$WD"
if [ "$1" == "plot" ]; then
    bin/grafs | python scripts/plot.py && open out/plot.png
else
    bin/grafs
fi
